### PR TITLE
Implement GUI features

### PR DESCRIPTION
**Pull request by sevenbunu**
- refactor functions read and write
- create separate view AlertDialog
- implement save and write graphs in csv-files
- make buttons of ford-bellman algorithm and cycles work

### CODE REVIEW

**Comment by ns-58** [comment]
image
issue: can't read csv file

**Comment by sevenbunu** [comment]
I changed functions of read and write graphs so it doesn't work with old graphs, but great deal with them:
[ex1.csv](https://github.com/user-attachments/files/15509339/ex1.csv)
[ex1analyzed.csv](https://github.com/user-attachments/files/15509340/ex1analyzed.csv)
[ex2.csv](https://github.com/user-attachments/files/15509341/ex2.csv)
[ex2analyzed.csv](https://github.com/user-attachments/files/15509342/ex2analyzed.csv)

**Comment by ns-58** [comment]
You've forgotten to implement vertex size rationing, haven't you?

**Comment by sevenbunu** [comment]
You're right!

**Review by vicitori — APPROVED** [review]

**Pull request merged**
